### ISSUE TITLE
Test prompt with 5 top free models and document results.

### ISSUE THREAD

**Issue by iramykytyn** [COXIT-CO/dont_trust_ai#7]
See a list of the most popular free models on open router or use the chatcraft.org free models list (since it might not always be indicated which models are free on openrouter).

Create a report showing whether any of the free models give good enough results compared to the GPT or Claude models.

**Comment by eLQeR** [comment]
All the experiments that were researched are described in the Google Docs below:
[Test prompt with 5 top free models](https://docs.google.com/document/d/1KYyhJe6TLXXiwgntpDTPEmZJKahSnopt_7Ky4gSDIQM/edit)

**Comment by iramykytyn** [comment]
Good job finding the cheap model with a GPT level of performance. Let's not focus more on cost optimization now but on accuracy for the 3 models that work best for us: GPT-4o , Claude-3.5-sonet and qwen-2-72b-instruct.
